### ISSUE TITLE
Make minima more tolerant to HTTP failures

### ISSUE THREAD

**Issue by juliogonzalez** [moio/minima#14]
For example, syncing from SCC today:
```
2019/06/20 15:47:54 Downloading (496/590) yast2-storage-ng-4.1.83-1.7.x86_64.rpm...
2019/06/20 15:48:00 Got unexpected status code from https://updates.suse.com/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product/x86_64/yast2-storage-ng-4.1.83-1.7.x86_64.rpm?XXXXXXXXX, 502
```
But retrying fixed the issue.

Maybe it was a problem at the mirror, (happens sometimes at openSUSE), so I think minima could have a configure parameter at `minima.yml` to specify how many retries (if any at all) minima should do before giving up, at least for HTTP errors (maybe for TCP errors as well).

**Comment by moio** [comment]
Currently it's 20 retries, not configurable:

https://github.com/moio/minima/blob/master/get/syncer.go#L119

Errors considered non-fatal are:

- 404 https://github.com/moio/minima/blob/master/get/syncer.go#L128
- package checksums not matching repo metadata checksums https://github.com/moio/minima/blob/master/get/syncer.go#L137
- package signatures not passing checks https://github.com/moio/minima/blob/master/get/syncer.go#L143

I wonder whether error 50x should be treated in the same way. In principle, `minima get` should be set on a frequent cron job by design.

**Comment by juliogonzalez** [comment]
I can't reproduce zypper and a 502:
```
# zypper ref                                                                                                                                                                                                                           
Retrieving repository 'test' metadata ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------[\]
Location 'http://test.mydomain.com/repodata/repomd.xml' is temporarily unaccessible.
Abort, retry, ignore? [a/r/i] (r): 
Trying again...
Location 'http://p2p.hispa-net.com/repodata/repomd.xml' is temporarily unaccessible.
Abort, retry, ignore? [a/r/i] (r): 
Autoselecting 'r' after 17 seconds.
```
In fact: https://bugzilla.suse.com/show_bug.cgi?id=1070851 and https://github.com/openSUSE/libzypp/pull/129/files

So it seems to me that zypper retries for:
- 401
- 403
- 404
- 410
- 502
- 503
- 504

Keep in mind that download.opensuse.org is a mirrordirector and I guess something similar happens for update.suse.com (not sure!), so you can very well get a 40X or 50X from one of the mirrors while if you retry everything will work fine.
